### ISSUE TITLE
Silly question

### ISSUE THREAD

**Issue by mspr1nt** [khylias/elementor-timeline-post#1]
Hello,

I'm not a developer so sorry if this is a dumb question - but how do I install this plugin? Is it through the usual WP channels or do I need to manually create my own widget using the code?

**Comment by khylias** [comment]
Hi @mspr1nt,

You can use this plugin by downloading it from the main screen, by clicking the download button > Download ZIP.
Then unzip the archive into the `/wp-content/plugins` folder of your Wordpress site.

You will then find in your dashboard > extensions, the possibility to activate Element Timeline Post, and enjoy ! 🤘
